### ISSUE TITLE
won't install

### ISSUE THREAD

**Issue by guyvanbael** [thezenmonkey/SilverStripe-RealEstateCMS#5]
testing this for a future project, but it won't install using composer.
![schermafbeelding 2016-11-04 om 11 08 30](https://cloud.githubusercontent.com/assets/3098809/20002094/52e845f2-a27f-11e6-9c88-79cc259f3582.png)

**Comment by thezenmonkey** [comment]
What's your timeline? Looks like a few of the dependcies need updating or replacing.

**Comment by guyvanbael** [comment]
Something like a fortnight

**Comment by thezenmonkey** [comment]
Okay. I'll test the updates over the week.

**Comment by thezenmonkey** [comment]
@guyvanbael the 3.3-Integrations branch so far seems pretty stable with ss3.4, I haven't notices any major issues. If you find anyting I'll try to update ASAP.

**Comment by guyvanbael** [comment]
update: my fault... i installed dev-master instead of 3-3 branch
@thezenmonkey stille having issues (server problem when reaching homepage class)

![schermafbeelding 2016-11-07 om 08 34 30](https://cloud.githubusercontent.com/assets/3098809/20049797/acc73e8c-a4c5-11e6-9e01-ba76aaa7b46a.png)
